### ISSUE TITLE
Append div with card class to html in js code

### ISSUE THREAD

**Issue by annarogala** [maslana-mucha/JS.Baby-Memory-Game#3]
```
<div class="card" data-name="blocks">
      <img class="front" src="./img/blocks.png" alt="Blocks" />
      <img class="back" src="./img/baby-game.png" alt="Card" />
</div>
```

Instead of hard coding these divs in html, please add in your js script an array with picture/file names (eg. `blocks`), iterate through it and append such div for each picture (twice) in ` <section class="game">`

**Comment by maslana-mucha** [comment]
Issue has been solved by adding a new function to create cards divs (createCards).
